version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/WebUi
hooks:
  BeforeInstall:
    - location: deploy/install_dep
      timeout: 300
      runas: root
    - location: deploy/start_server
      timeout: 300
      runas: root

  ApplicationStop:
    - location: deploy/stop_server
      timeout: 300
      runas: root