version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: deploy/install_dep
      timeout: 300
      runas: root
    - location: deploy/start_server
      timeout: 300
      runas: root

  ApplicationStop:
    - location: deplop/stop_server
      timeout: 300
      runas: root